# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :beta do
    setup_ci if ENV['CI']
    match(type: 'appstore')
    update_project_team
    update_code_signing_settings(code_sign_identity: "iPhone Distribution")
    api_key = app_store_connect_api_key
    current_build_number = app_store_build_number(live: false, api_key: api_key)
    increment_build_number(build_number: current_build_number + 1)
    build_app(scheme: "App")
    upload_to_testflight(skip_waiting_for_build_processing: true, api_key: api_key)
  end
end

platform :android do
  lane :beta do
    setup_ci if ENV['CI']
    build_android_app(task: "assemble")
    upload_to_play_store(track: 'internal')
  end
end
