name: deploy to appstore
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: git clone --depth 1 https://github.com/traccar/traccar-web
      - run: |
          cp -v ../capacitor.* .
          npm install -D @capacitor/cli @capacitor/core @capacitor/ios typescript
          npx cap add ios
          mv -v ../fastlane ios/App
        working-directory: traccar-web
        env:
          APP_ID: ${{ vars.APP_ID }}
          APP_NAME: ${{ vars.APP_NAME }}
      - run: |
          echo '${{ secrets.GOOGLE_CLOUD_AUTH }}' >> gc_keys.json
          fastlane beta
        working-directory: traccar-web/ios/App
        env:
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APPSTORE_API_KEY }}
          APP_IDENTIFIER: ${{ vars.APP_IDENTIFIER }}
          TEAM_ID: ${{ vars.TEAM_ID }}
          APPLE_ID: ${{ vars.APPLE_ID }}
          FL_PROVISIONING_PROFILE_SPECIFIER: ${{ vars.FL_PROVISIONING_PROFILE_SPECIFIER }}
