name: deploy to appstore
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: git clone --depth 1 https://github.com/traccar/traccar-web
      - run: npm ci
        working-directory: traccar-web
      - run: |
          cp -v capacitor.* traccar-web
          mv fastlane traccar-web
      - run: |
          npm install -D @capacitor/cli @capacitor/core @capacitor/ios typescript
          npx cap add ios
          echo '${{ secrets.GOOGLE_CLOUD_AUTH }}' >> ./ios/App/gc_keys.json
          fastlane beta
        working-directory: traccar-web
        env:
          APP_ID: ${{ vars.APP_ID }}
          APP_NAME: ${{ vars.APP_NAME }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APPSTORE_API_KEY }}
